spring:
  application:
    name: customer-service

  datasource:
    url: jdbc:mysql://localhost:3306/customer_master  
    driver-class-name: com.mysql.cj.jdbc.Driver       
    username: root                                     
    password: Php@1234                         

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
