global:
  message: welcome to order service dev environment

server:
  port: 8084

message: Hello from order Dev

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_master
    username: root                                     
    password: Ajayv@10     
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
